services:
  app:
    image: crisdegraciadev/comet:latest
    environment:
      PHX_SERVER: "true"
      PHX_HOST: "localhost"
      SECRET_KEY_BASE: "dKhseTrfL/BGZosW4sPMM9EoG+Be0IRf+mrMlaolAStkJN4O9OrubatPZ0eV5I86"
    ports:
      - "4001:4000"
    networks:
      - comet_net
    command: /bin/sh -c "/app/bin/comet eval 'Comet.Release.migrate' && /app/bin/comet start"


networks:
  comet_net:
